/**
 * Shared property-based money-math parity test (#239)
 *
 * Loads the deterministic JSON corpus generated by
 * `shared-test-fixtures/generate-corpus.js` and verifies that the TypeScript
 * fee/loss/clawback calculations match the expected values.
 *
 * This ensures parity between TypeScript (off-chain) and Rust (on-chain)
 * implementations of the same arithmetic.
 */
import * as fs from "fs";
import * as path from "path";

// ── Corpus types ─────────────────────────────────────────────────────────────

interface Corpus {
  generator: {
    seed: number;
    generated_cases: number;
    bps_divisor: number;
    timestamp: string;
  };
  invariants: string[];
  fixtures: {
    fee_boundary: FeeCase[];
    fee_generated: FeeCase[];
    loss_boundary: LossCase[];
    release_funds_conservation: ReleaseCase[];
    resolve_dispute_conservation: DisputeCase[];
    clawback_conservation: ClawbackCase[];
  };
}

interface FeeCase {
  id: number;
  amount: number;
  fee_bps: number;
  expected_fee: number;
  expected_seller_amount: number;
}

interface LossCase {
  id: number;
  total: number;
  loss_bps: number;
  seller_loss_bps: number;
  expected_loss: number;
}

interface ReleaseCase {
  id: number;
  amount: number;
  fee_bps: number;
  seller_amount: number;
  fee_amount: number;
  sum_equals_amount: boolean;
}

interface DisputeCase {
  id: number;
  total: number;
  seller_gets_bps: number;
  buyer_loss_bps: number;
  seller_loss_bps: number;
  fee_bps: number;
  seller_loss: number;
  seller_raw: number;
  buyer_refund: number;
  fee: number;
  seller_net: number;
  sum_equals_total: boolean;
  all_non_negative: boolean;
}

interface ClawbackCase {
  id: number;
  trade_amount: number;
  clawback_amount: number;
  expected_remaining: number;
  expected_clawback_total: number;
  full_clawback: boolean;
}

// ── Production helpers (mirrors Rust lib.rs) ─────────────────────────────────

const BPS_DIVISOR = 10_000;

function checkedFeeAmount(amount: number, feeBps: number): number {
  return Math.floor((amount * feeBps) / BPS_DIVISOR);
}

function checkedLossAmount(
  total: number,
  lossBps: number,
  sellerLossBps: number
): number {
  return Math.floor(
    (total * lossBps * sellerLossBps) / (BPS_DIVISOR * BPS_DIVISOR)
  );
}

// ── Corpus loader ────────────────────────────────────────────────────────────

function loadCorpus(): Corpus {
  const corpusPath = path.resolve(
    __dirname,
    "../money_math_corpus.json"
  );
  const data = fs.readFileSync(corpusPath, "utf-8");
  return JSON.parse(data);
}

// ── Tests ────────────────────────────────────────────────────────────────────

describe("Shared money-math corpus", () => {
  let corpus: Corpus;

  beforeAll(() => {
    corpus = loadCorpus();
  });

  describe("Corpus metadata", () => {
    it("has correct BPS divisor", () => {
      expect(corpus.generator.bps_divisor).toBe(BPS_DIVISOR);
    });

    it("has >= 1000 generated cases", () => {
      expect(corpus.generator.generated_cases).toBeGreaterThanOrEqual(1000);
    });

    it("documents all 8 invariants", () => {
      expect(corpus.invariants.length).toBeGreaterThanOrEqual(8);
    });
  });

  describe("Fee boundary parity", () => {
    it.each(corpus.fixtures.fee_boundary)(
      "case #$id: amount=$amount, bps=$fee_bps",
      (c) => {
        const tsFee = checkedFeeAmount(c.amount, c.fee_bps);
        expect(tsFee).toBe(c.expected_fee);

        const seller = c.amount - tsFee;
        expect(seller).toBe(c.expected_seller_amount);
      }
    );
  });

  describe("Fee generated parity", () => {
    it.each(corpus.fixtures.fee_generated)(
      "case #$id: amount=$amount, bps=$fee_bps",
      (c) => {
        const tsFee = checkedFeeAmount(c.amount, c.fee_bps);
        expect(tsFee).toBe(c.expected_fee);
      }
    );
  });

  describe("Loss boundary parity", () => {
    it.each(corpus.fixtures.loss_boundary)(
      "case #$id: total=$total, loss_bps=$loss_bps, sl_bps=$seller_loss_bps",
      (c) => {
        const tsLoss = checkedLossAmount(c.total, c.loss_bps, c.seller_loss_bps);
        expect(tsLoss).toBe(c.expected_loss);
      }
    );
  });

  describe("Release funds conservation", () => {
    it("all cases satisfy seller + fee == amount", () => {
      for (const c of corpus.fixtures.release_funds_conservation) {
        const tsFee = checkedFeeAmount(c.amount, c.fee_bps);
        const tsSeller = c.amount - tsFee;

        // Invariant: seller_amount + fee_amount == amount
        expect(tsSeller + tsFee).toBe(c.amount);

        // Parity with expected values
        expect(tsFee).toBe(c.fee_amount);
        expect(tsSeller).toBe(c.seller_amount);

        // Non-negative
        expect(tsSeller).toBeGreaterThanOrEqual(0);
        expect(tsFee).toBeGreaterThanOrEqual(0);
      }
    });
  });

  describe("Resolve dispute conservation", () => {
    it("all cases satisfy seller_net + buyer_refund + fee == total", () => {
      for (const c of corpus.fixtures.resolve_dispute_conservation) {
        const lossBps = BPS_DIVISOR - c.seller_gets_bps;

        const tsLoss = checkedLossAmount(c.total, lossBps, c.seller_loss_bps);
        const tsSellerRaw = c.total - tsLoss;
        const tsBuyerRefund = c.total - tsSellerRaw;
        const tsFee = checkedFeeAmount(tsSellerRaw, c.fee_bps);
        const tsSellerNet = tsSellerRaw - tsFee;

        // Invariant: seller_net + buyer_refund + fee == total
        expect(tsSellerNet + tsBuyerRefund + tsFee).toBe(c.total);

        // All non-negative
        expect(tsSellerNet).toBeGreaterThanOrEqual(0);
        expect(tsBuyerRefund).toBeGreaterThanOrEqual(0);
        expect(tsFee).toBeGreaterThanOrEqual(0);

        // Parity with expected values
        expect(tsLoss).toBe(c.seller_loss);
        expect(tsSellerRaw).toBe(c.seller_raw);
        expect(tsBuyerRefund).toBe(c.buyer_refund);
        expect(tsFee).toBe(c.fee);
        expect(tsSellerNet).toBe(c.seller_net);
      }
    });
  });

  describe("Clawback conservation", () => {
    it("all cases satisfy remaining + clawback == trade_amount", () => {
      for (const c of corpus.fixtures.clawback_conservation) {
        const remaining = c.trade_amount - c.clawback_amount;

        expect(remaining).toBe(c.expected_remaining);
        expect(remaining + c.clawback_amount).toBe(c.trade_amount);

        if (c.full_clawback) {
          expect(remaining).toBe(0);
        }
      }
    });
  });
});
