/// Shared property-based money-math parity test (#239)
///
/// Loads the deterministic JSON corpus generated by
/// `shared-test-fixtures/generate-corpus.js` and verifies that the Rust
/// contract's fee/loss/clawback calculations match the expected values.
///
/// This ensures parity between Rust (on-chain) and TypeScript (off-chain)
/// implementations of the same arithmetic.
use serde::Deserialize;
use std::fs;
use std::path::Path;

// ── Corpus types ─────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Corpus {
    generator: GeneratorMeta,
    fixtures: Fixtures,
}

#[derive(Debug, Deserialize)]
struct GeneratorMeta {
    seed: u64,
    generated_cases: u64,
    bps_divisor: i128,
}

#[derive(Debug, Deserialize)]
struct Fixtures {
    fee_boundary: Vec<FeeCase>,
    fee_generated: Vec<FeeCase>,
    loss_boundary: Vec<LossCase>,
    release_funds_conservation: Vec<ReleaseCase>,
    resolve_dispute_conservation: Vec<DisputeCase>,
    clawback_conservation: Vec<ClawbackCase>,
}

#[derive(Debug, Deserialize)]
struct FeeCase {
    id: u64,
    amount: i128,
    fee_bps: u32,
    expected_fee: i128,
    expected_seller_amount: i128,
}

#[derive(Debug, Deserialize)]
struct LossCase {
    id: u64,
    total: i128,
    loss_bps: i128,
    seller_loss_bps: u32,
    expected_loss: i128,
}

#[derive(Debug, Deserialize)]
struct ReleaseCase {
    id: u64,
    amount: i128,
    fee_bps: u32,
    seller_amount: i128,
    fee_amount: i128,
    sum_equals_amount: bool,
}

#[derive(Debug, Deserialize)]
struct DisputeCase {
    id: u64,
    total: i128,
    seller_gets_bps: u32,
    buyer_loss_bps: u32,
    seller_loss_bps: u32,
    fee_bps: u32,
    seller_loss: i128,
    seller_raw: i128,
    buyer_refund: i128,
    fee: i128,
    seller_net: i128,
    sum_equals_total: bool,
    all_non_negative: bool,
}

#[derive(Debug, Deserialize)]
struct ClawbackCase {
    id: u64,
    trade_amount: i128,
    clawback_amount: i128,
    expected_remaining: i128,
    expected_clawback_total: i128,
    full_clawback: bool,
}

// ── Production helpers (mirrors lib.rs) ──────────────────────────────────────

const BPS_DIVISOR: i128 = 10_000;

fn checked_fee_amount(amount: i128, fee_bps: u32) -> Option<i128> {
    amount.checked_mul(fee_bps as i128).map(|v| v / BPS_DIVISOR)
}

fn checked_loss_amount(total: i128, loss_bps: i128, seller_loss_bps: u32) -> Option<i128> {
    total
        .checked_mul(loss_bps)
        .and_then(|v| v.checked_mul(seller_loss_bps as i128))
        .map(|v| v / (BPS_DIVISOR * BPS_DIVISOR))
}

// ── Loader ───────────────────────────────────────────────────────────────────

fn load_corpus() -> Corpus {
    // The corpus is at the repo root relative to the workspace Cargo.toml
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let corpus_path = Path::new(manifest_dir)
        .join("../../shared-test-fixtures/money_math_corpus.json");

    let data = fs::read_to_string(&corpus_path)
        .unwrap_or_else(|e| panic!("Failed to read corpus at {:?}: {}", corpus_path, e));

    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Failed to parse corpus JSON: {}", e))
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[test]
fn corpus_metadata() {
    let corpus = load_corpus();
    assert_eq!(corpus.generator.bps_divisor, BPS_DIVISOR);
    assert!(
        corpus.generator.generated_cases >= 1000,
        "Corpus must have >= 1000 generated cases, got {}",
        corpus.generator.generated_cases
    );
}

#[test]
fn fee_boundary_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.fee_boundary {
        let rust_fee = checked_fee_amount(case.amount, case.fee_bps)
            .unwrap_or_else(|| panic!("Rust fee overflowed at case #{}", case.id));
        assert_eq!(
            rust_fee, case.expected_fee,
            "Fee mismatch at case #{}: amount={}, bps={}, rust={}, expected={}",
            case.id, case.amount, case.fee_bps, rust_fee, case.expected_fee
        );
        let seller = case.amount - rust_fee;
        assert_eq!(
            seller, case.expected_seller_amount,
            "Seller amount mismatch at case #{}",
            case.id
        );
    }
}

#[test]
fn fee_generated_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.fee_generated {
        let rust_fee = checked_fee_amount(case.amount, case.fee_bps)
            .unwrap_or_else(|| panic!("Rust fee overflowed at case #{}", case.id));
        assert_eq!(
            rust_fee, case.expected_fee,
            "Fee mismatch at case #{}: amount={}, bps={}, rust={}, expected={}",
            case.id, case.amount, case.fee_bps, rust_fee, case.expected_fee
        );
    }
}

#[test]
fn loss_boundary_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.loss_boundary {
        let rust_loss = checked_loss_amount(case.total, case.loss_bps, case.seller_loss_bps)
            .unwrap_or_else(|| panic!("Rust loss overflowed at case #{}", case.id));
        assert_eq!(
            rust_loss, case.expected_loss,
            "Loss mismatch at case #{}: total={}, loss_bps={}, sl_bps={}, rust={}, expected={}",
            case.id, case.total, case.loss_bps, case.seller_loss_bps, rust_loss, case.expected_loss
        );
    }
}

#[test]
fn release_funds_conservation_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.release_funds_conservation {
        let rust_fee = checked_fee_amount(case.amount, case.fee_bps)
            .unwrap_or_else(|| panic!("Rust fee overflowed at case #{}", case.id));
        let rust_seller = case.amount - rust_fee;

        // Invariant: seller_amount + fee_amount == amount
        assert_eq!(
            rust_seller + rust_fee,
            case.amount,
            "Release conservation violated at case #{}",
            case.id
        );

        // Parity: Rust values match expected
        assert_eq!(
            rust_fee, case.fee_amount,
            "Fee parity mismatch at case #{}",
            case.id
        );
        assert_eq!(
            rust_seller, case.seller_amount,
            "Seller amount parity mismatch at case #{}",
            case.id
        );
    }
}

#[test]
fn resolve_dispute_conservation_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.resolve_dispute_conservation {
        let loss_bps = BPS_DIVISOR - case.seller_gets_bps as i128;

        let rust_seller_loss = checked_loss_amount(case.total, loss_bps, case.seller_loss_bps)
            .unwrap_or_else(|| panic!("Rust loss overflowed at case #{}", case.id));
        let rust_seller_raw = case.total - rust_seller_loss;
        let rust_buyer_refund = case.total - rust_seller_raw;
        let rust_fee = checked_fee_amount(rust_seller_raw, case.fee_bps)
            .unwrap_or_else(|| panic!("Rust fee overflowed at case #{}", case.id));
        let rust_seller_net = rust_seller_raw - rust_fee;

        // Invariant: seller_net + buyer_refund + fee == total
        assert_eq!(
            rust_seller_net + rust_buyer_refund + rust_fee,
            case.total,
            "Dispute conservation violated at case #{}",
            case.id
        );

        // All non-negative
        assert!(rust_seller_net >= 0, "seller_net < 0 at case #{}", case.id);
        assert!(
            rust_buyer_refund >= 0,
            "buyer_refund < 0 at case #{}",
            case.id
        );
        assert!(rust_fee >= 0, "fee < 0 at case #{}", case.id);

        // Parity with expected values
        assert_eq!(rust_seller_loss, case.seller_loss, "seller_loss parity at case #{}", case.id);
        assert_eq!(rust_seller_raw, case.seller_raw, "seller_raw parity at case #{}", case.id);
        assert_eq!(rust_buyer_refund, case.buyer_refund, "buyer_refund parity at case #{}", case.id);
        assert_eq!(rust_fee, case.fee, "fee parity at case #{}", case.id);
        assert_eq!(rust_seller_net, case.seller_net, "seller_net parity at case #{}", case.id);
    }
}

#[test]
fn clawback_conservation_parity() {
    let corpus = load_corpus();
    for case in &corpus.fixtures.clawback_conservation {
        // Invariant: remaining + clawback_amount == trade_amount
        let remaining = case.trade_amount - case.clawback_amount;
        assert_eq!(
            remaining, case.expected_remaining,
            "Clawback remaining mismatch at case #{}",
            case.id
        );
        assert_eq!(
            remaining + case.clawback_amount,
            case.trade_amount,
            "Clawback conservation violated at case #{}",
            case.id
        );

        // Edge: full clawback transitions to zero
        if case.full_clawback {
            assert_eq!(
                remaining, 0,
                "Full clawback should leave 0 at case #{}",
                case.id
            );
        }
    }
}
